// Write a C++ program that demonstrate working of operator overloading.
// Code generated by notion AI
#include<iostream>
using namespace std;
class Complex{
    private:
        int real, imag;
    public:
        Complex(int r=0, int i=0){
            real = r;
            imag = i;
        }
        Complex operator + (Complex const &obj){
            Complex res;
            res.real = real + obj.real;
            res.imag = imag + obj.imag;
            return res;
        }
        void print(){
            cout << real << " + i" << imag << endl;
        }
};
int main(){
    Complex c1(5, 10), c2(10, 5);
    Complex c3 = c1 + c2;
    c3.print();
    return 0;
}
